### ISSUE TITLE
Date appended to dhcpv4 fingerprint in SQlite database

### ISSUE THREAD

**Issue by nayabbashasayed** [inverse-inc/fingerbank#36]
Downloaded SQlite database.
I was querying a fingerprint for a particular id using the sqlite api like following:
`sqlite3_exec(&db, "SELECT value FROM dhcp_fingerprint WHERE id = 36782;", callback, NULL, NULL);`
It gave following result:
`1,15,3,6,44,46,47,32016-11-04`, fingerprint appended by date.
I verified this using CLI, the result:

```
.
.
.
> 36780       1,3,4,6,12,15,28,42,43,60,3,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,  2016-11-03  2016-11-03  0         
> 36781       1,121,3,6,15,119,2522016-11-04                                                                        2016-11-03  2016-11-03  0         
> 36782       1,15,3,6,44,46,47,32016-11-04                                                                         2016-11-03  2016-11-03  0         
```
So Why date is appended to fingerprint when there is a `created_at` field? It makes harder to search for a fingerprint in database using SQlite API.

**Comment by julsemaan** [comment]
This was garbage data sent by some users.

There is currently no validation of that field (there isn't on any of the fingerbank fields)

You can safely ignore those.

We will add validation of the field to the dhcp_fingerprint and dhcp6_fingerprint fields at the API level and cleanup inaccurate data.

I'm closing the issue here because this repo has moved to https://github.com/fingerbank/cloud-api but it will be addressed eventually

**Comment by julsemaan** [comment]
See 
https://github.com/fingerbank/cloud-api/issues/4
